version: '3.6'
# Deploys Bigchaindb 
# usage:
# sudo docker-compose up


services:
  bigchaindb-all:
    image: grydl/bigchaindb:all-in-one
    container_name: grydl_bigchaindb
    ports:
      - 9984:9984
      - 9985:9985
      - 27017:27017
      - 26657:26657
    volumes:
      #  configuration and data folders
      - ./bigchaindb_docker/mongodb/data/db:/data/db
      - ./bigchaindb_docker/mongodb/data/configdb:/data/configdb
      - ./bigchaindb_docker/tendermint:/tendermint
    networks:
      - bigchain_net

networks:
  bigchain_net:
    driver: bridge